Update to new rule syntax
graknlabs/behaviour pull request #103
Opened 2020-10-06 15:25 UTC by flyingsilverfin

## What is the goal of this PR?
Find and replace the remaining uses of rules that were not updated to the new rule syntax of:
```
define/undefine
rule xyz: when { ... } then { ... }
```

## What are the changes implemented in this PR?
* Replace rule define and undefines with new rule syntax

2020-10-06 16:18 UTC, alexjpwalker commented on graql/language/rule-validation.feature
>        has-nickname-bob sub rule,
```suggestion
      rule has-nickname-bob:
```

2020-10-06 16:25 UTC, alexjpwalker requested changes
Suggested a change

2020-10-06 16:30 UTC, alexjpwalker approved these changes

2020-10-07 09:28 UTC, jmsfltchr approved these changes

2020-10-07 09:34 UTC, merged