Add Update query tests
graknlabs/behaviour pull request #161
Opened 2021-02-02 12:04 UTC by Phillammon

## What is the goal of this PR?

We added a new query type, so we needed to add tests to cover this new query type (or at least, the parts unique to it, as match, insert and delete have fairly good coverage of it).

## What are the changes implemented in this PR?

Added `update.feature`

2021-02-02 12:31 UTC, jmsfltchr requested changes

2021-02-02 12:31 UTC, jmsfltchr commented on graql/language/update.feature
> +Feature: Graql Delete Query
`Graql Update Query`

2021-02-02 12:31 UTC, jmsfltchr commented on graql/language/update.feature
> +  Scenario: simple update
Capitalise first word

2021-02-02 12:31 UTC, jmsfltchr commented on graql/language/update.feature
> +  ##########
If this comment for consistency with elsewhere? If not it's meaningless as we're always talking things.

2021-02-02 12:31 UTC, jmsfltchr commented on graql/language/update.feature
> +  Scenario: simple update
Also this scenario does more, it updates one instance without side effects on the other, so try to put that in the title.

2021-02-02 12:31 UTC, jmsfltchr commented on graql/language/update.feature
> +        $r (friend: $y);
Good test case, are there any other invalid states we could put ourselves into? We could take inspiration from our other existing tests.

2021-02-02 12:31 UTC, jmsfltchr commented on graql/language/update.feature
> +    Then transaction commits
Isn't there a value to doing the match and checking the answers? Otherwise how do we know this was successful?

2021-02-02 22:19 UTC, haikalpribadi requested changes
I'm leaving the detailed review of the scenarios to @jmsfltchr, so I'm just commenting on the overall formatting: if there are multiple lines of `match/delete/insert` variables, put them on a new line but at the same indentation, not deeper. If not multiple lines keep them on the same line as `match/delete/insert` keyword.

2021-02-03 11:52 UTC, jmsfltchr approved these changes

2021-02-03 14:46 UTC, haikalpribadi approved these changes

2021-02-03 14:47 UTC, merged